---

- hosts: localhost

  vars:
          zabbix_server:  http://localhost:80


  tasks:
  - name: Dump Zabbix template
    local_action:
        module: zabbix_template
        server_url: http://localhost
        login_user: Admin
        login_password: zabbix
        template_name: Template App Zabbix Agent
        state: dump
    register: template_dump
  
  - copy: content={{ template_dump }}  dest=export_zabbix_agent.template
    

