---

- hosts: localhost

  vars:
     zabbix_server:  localhost:8090

  
  tasks:

   # Export template json definition
    - name: Dump Zabbix template
      local_action:
        module: zabbix_template
        server_url: http://127.0.0.1
        login_user: username
        login_password: password
        template_name: Template
        state: dump
      register: template_dump
    
